name: Trigger Update

on:
  workflow_dispatch:  # This allows manual triggering from GitHub Actions UI

jobs:
  download-release:
    runs-on: windows-latest
    steps:
    - name: Trigger GitHub API to update binaries
      run: |
        curl \
            -X POST \
          -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/MahBoiDeveloper/TwistedInsurrectionUpdatedClient/actions/workflows/UpdateClientBinaries.yml/dispatches \
            -d '{"ref":"main"}'
