name: Trigger Update

on:
  workflow_dispatch:  # This allows manual triggering from GitHub Actions UI

jobs:
  update:
    runs-on: windows-latest
    steps:
    - name: Trigger GitHub API to update binaries
      run: |
        gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/MahBoiDeveloper/TwistedInsurrectionUpdatedClient/actions/workflows/UpdateClientBinaries.yml/dispatches
