name: Update XNA CnCNet Client

on:
  workflow_dispatch:

env:
  REPO_NAME: TwistedInsurrectionUpdatedClient
  UPDATE_BRANCH_NAME: update-client-binaries
  COMMIT_MESSAGE: Update client binaries to the latest version
  PR_TITLE: Update client binaries to the version
  PR_BODY: This is an automatic pull request to update client binaries triggered from CnCNet/xna-cncnet-client repository.

jobs:
  publish-update-pr:
    runs-on: windows-2022

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
      with:
        lfs: true
    
    - name: Download Latest Release
      id: download
      uses: robinraju/release-downloader@v1
      with:
        repository: CnCNet/xna-cncnet-client
        latest: true
        fileName: xna-cncnet-client*

    - name: Compare Versions
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $currentVersion = (Get-Item -Path "D:\a\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}\Resources\clientdx.exe").VersionInfo.FileVersion -Replace "\.0$", ""
        $downloadVersion = '${{ steps.download.outputs.tag_name }}'
        
        echo ${{ steps.download.outputs.tag_name }}

        echo "current_version=$currentVersion" >> $GITHUB_OUTPUT
        echo "download_version=$downloadVersion" >> $GITHUB_OUTPUT

        echo "Current client version: '$currentVersion'"
        echo "Downloaded client version: '$downloadVersion'"

        if ($currentVersion -eq $downloadVersion) {
          echo "update_required=false" >> $GITHUB_OUTPUT
          echo "Update doesn't required"
          throw "Update doesn't required" 
        } else {
          echo "update_required=true" >> $GITHUB_OUTPUT
          echo "Update required"
          
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git branch -D ${{ env.UPDATE_BRANCH_NAME }}
          git checkout -b ${{ env.UPDATE_BRANCH_NAME }}
          
          rm -r -fo "D:\a\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}\Resources\Binaries"
          rm -r -fo "D:\a\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}\Resources\BinariesNET8"
          7z x xna-cncnet-client-*.7z -y -oD:\a\${{ env.REPO_NAME }}\${{ env.REPO_NAME }}
          rm xna-cncnet-client-*.7z

          git commit -am "${{ env.COMMIT_MESSAGE }}"
          git push --force origin ${{ env.UPDATE_BRANCH_NAME }}

          # timeout /t 10
          gh pr create -B main -H ${{ env.UPDATE_BRANCH_NAME }} --title '${{ env.PR_TITLE }} ${{ steps.download.outputs.tag_name }}' --body '${{ env.PR_BODY }}'
        }
        
    - name: Open PR
      if: ${{ success() }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr create -B main -H ${{ env.UPDATE_BRANCH_NAME }} --title '${{ env.PR_TITLE }} ${{ steps.download.outputs.tag_name }}' --body '${{ env.PR_BODY }}'

