name: Update XNA CnCNet Client Release

on:
  workflow_dispatch:  # This allows manual triggering from GitHub Actions UI

jobs:
  download-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Download latest XNA client release
      uses: robinraju/release-downloader@v1
      with:
        repository: CnCNet/xna-cncnet-client
        latest: true
        fileName: xna-cncnet-client*

    - name: Extract release contents
      run: |
        7z x xna-cncnet-client-*.7z -oD:\a\TwistedInsurrectionUpdatedClient
        rm xna-cncnet-client-*.7z

    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Check for changes
      id: check_changes
      run: |
        if (git status --porcelain) {
          echo "changed=true" >> $env:GITHUB_ENV
        } else {
          echo "changed=false" >> $env:GITHUB_ENV
        }

    - name: Commit and push changes
      if: env.changed == 'true'
      run: |
        $branch = "update-xna-client"
        git checkout -b $branch
        git add Resources
        git commit -m "Update XNA CnCNet Client binaries"
        git push origin $branch

    - name: Create Pull Request
      if: env.changed == 'true'
      run: gh pr create -B main -H update-xna-client --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
